# -------------------------------------------------------------------------------------
# Theme Core Configuration
# -------------------------------------------------------------------------------------

# site description
description = "工坊创造之源也，活的知识结构，分享一些所见、所闻、所思"

# site keywords
keywords = ["家园工程", "家园工程的工坊", "SevenD", "Seven", "Home Project", "HomeProject", "JYGC"]

# site default theme ("light", "dark", "auto")
defaultTheme = "auto"
# date format
dateFormat = "2006-01-02"

# website images for Open Graph and Twitter Cards
images = ["/images/apple-devices-preview.webp"]
# FixIt 0.2.12 | NEW enable PWA
enablePWA = true
# FixIt 0.2.14 | NEW whether to add external Icon for external links automatically
externalIcon = true
# FixIt 0.3.13 | NEW whether to capitalize titles
capitalizeTitles = true
# FixIt 0.3.0 | NEW whether to add site title to the title of every page
# remember to set up your site title in `hugo.toml` (e.g. title = "title")
withSiteTitle = true
# FixIt 0.3.0 | NEW title delimiter when the site title is be added to the title of every page
titleDelimiter = "|"
# FixIt 0.3.0 | NEW whether to add site subtitle to the title of index page
# remember to set up your site subtitle by `params.header.subtitle.name`
indexWithSubtitle = true
# FixIt 0.3.13 | NEW whether to show summary in plain text
summaryPlainify = false
# FixIt 0.2.14 | NEW FixIt will, by default, inject a theme meta tag in the HTML head on the home page only.
# You can turn it off, but we would really appreciate if you don’t, as this is a good way to watch FixIt's popularity on the rise.
disableThemeInject = false

# Author Configuration
[author]
  name = "SevenD"
  email = "enter775@msn.com"
  link = "https://01235670.xyz/"
  avatar = "/images/avatar.jpg"

[header]
  # FixIt 0.2.13 | CHANGED desktop header mode ("sticky", "normal", "auto")
  desktopMode = "sticky"
  # FixIt 0.2.13 | CHANGED mobile header mode ("sticky", "normal", "auto")
  mobileMode = "auto"
  # Header title config
  [header.title]
    # URL of the LOGO
    logo = "/logo.webp"
    # title name
    name = "家園工程的工坊"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # whether to use typeit animation for title name
    typeit = false
  # FixIt 0.2.12 | NEW Header subtitle config
  [header.subtitle]
    # subtitle name
    name = "道生一、一生二、二生三、三生萬物"
    # whether to use typeit animation for subtitle name
    typeit = false

# Footer config
[footer]
  enable = true
  # FixIt 0.2.17 | CHANGED Custom content (HTML format is supported)
  # whether to show copyright info
  copyright = true
  # whether to show the author
  author = true
  # Site creation year
  since = 2018
  # FixIt 0.2.12 | NEW Public network security only in China (HTML format is supported)
  gov = ""
  # ICP info only in China (HTML format is supported)
  icp = ""
  # license info (HTML format is supported)
  license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
  # FixIt 0.3.0 | NEW whether to show Hugo and theme info
  [footer.powered]
    enable = true
    hugoLogo = true
    themeLogo = true
  # FixIt 0.2.17 | CHANGED Site creation time
  [footer.siteTime]
    enable = true
    animate = true
    icon = "fa-solid fa-heartbeat"
    pre = "博客已运行"
    value = "2018-05-28T20:01:01+08:00"
  # FixIt 0.2.17 | NEW footer lines order, optional values: ["first", 0, 1, 2, 3, 4, 5, "last"]
  [footer.order]
    powered = 1
    copyright = 2
    statistics = 3
    visitor = 4
    beian = 5

# List (category or tag) page config
[list]
  # special amount of posts in each list page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # FixIt 0.3.10 | NEW Term list feed config for RSS, Atom and JSON feed.
  [list.feed]
    # The number of posts to include in the feed. Default is -1, which means all posts.
    limit = -1
    # whether to show the full text content in feed.
    fullText = false

# FixIt 0.3.13 | NEW recently updated pages config for archives, section and term list
[recentlyUpdated]
  archives = true
  section = true
  term = true
  rss = false
  days = 30
  maxCount = 10

# FixIt 0.2.17 | NEW TagCloud config for tags page
[tagcloud]
  enable = true
  min = 14 # Minimum font size in px
  max = 32 # Maximum font size in px
  peakCount = 10 # Maximum count of posts per tag
  orderby = "name" # Order of tags, optional values: ["name", "count"]


# Home page config
[home]
  # amount of RSS pages
  rss = 20
  # Home page profile
  [home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "/images/avatar.jpg"
    # FixIt 0.2.17 | NEW identifier of avatar menu link
    avatarMenu = "about"
    # title shown in home page (HTML format is supported)
    title = "SevenD's Blog"
    # subtitle shown in home page
    subtitle = "萬物負陰而抱陽，中炁以為和"
    # whether to use typeit animation for subtitle
    typeit = true
    # whether to show social links
    social = true
    # disclaimer (HTML format is supported)
    disclaimer = ""
  # Home page posts
  [home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 10




# Page config
[page]
  # FixIt 0.2.18 | NEW whether to enable the author's avatar of the post
  authorAvatar = true
  # whether to hide a page from home page
  hiddenFromHomePage = false
  # whether to hide a page from search results
  hiddenFromSearch = false
  # FixIt 0.3.0 | NEW whether to hide a page from related posts
  hiddenFromRelated = false
  # FixIt 0.3.10 | NEW whether to hide a page from RSS, Atom and JSON feed
  hiddenFromFeed = false
  # whether to enable twemoji
  twemoji = false
  # whether to enable lightgallery
  lightgallery = "force"
  # whether to enable the ruby extended syntax
  ruby = true
  # whether to enable the fraction extended syntax
  fraction = true
  # whether to enable the fontawesome extended syntax
  fontawesome = true
  # Default lisence of content.
  license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
  # whether to show link to Raw Markdown content of the post
  linkToMarkdown = true
  # FixIt 0.3.0 | NEW whether to show link to view source code of the post
  linkToSource = true
  # FixIt 0.3.0 | NEW whether to show link to edit the post
  linkToEdit = true
  # FixIt 0.3.0 | NEW whether to show link to report issue for the post
  linkToReport = true
  # FixIt 0.2.13 | NEW Page style ("narrow", "normal", "wide", ...)
  pageStyle = "normal"
  # FixIt 0.2.17 | CHANGED Auto Bookmark Support
  # If true, save the reading progress when closing the page.
  autoBookmark = true
  # FixIt 0.2.17 | NEW whether to enable wordCount
  wordCount = true
  # FixIt 0.2.17 | NEW whether to enable readingTime
  readingTime = true
  # FixIt 0.2.17 | NEW end of post flag
  # endFlag = "（本文完）"
  endFlag = "「本文完，更多内容汇总在我的 GitHub，持续更新，求关注、求 star、求订阅！」"
  # FixIt 0.2.18 | NEW whether to enable instant.page
  instantPage = true
  # FixIt 0.3.0 | NEW whether to enable collection list at the sidebar
  collectionList = true
  # FixIt 0.3.0 | NEW whether to enable collection navigation at the end of the post
  collectionNavigation = true

  # Table of the contents config
  [page.toc]
    # whether to enable the table of the contents
    enable = true
    #  whether to keep the static table of the contents in front of the post
    keepStatic = false
    # whether to make the table of the contents in the sidebar automatically collapsed
    auto = true
    # FixIt 0.2.13 | NEW position of TOC ("left", "right")
    position = "right"
    # FixIt 0.3.12 | NEW supersede `markup.tableOfContents` settings
    ordered = true
    startLevel = 2
    endLevel = 6
  # FixIt 0.2.13 | NEW Display a message at the beginning of an article to warn the reader that its content might be expired
  [page.expirationReminder]
    enable = true
    # Display the reminder if the last modified time is more than 90 days ago
    reminder = 90
    # Display warning if the last modified time is more than 180 days ago
    warning = 180
    # If the article expires, close the comment or not
    closeComment = true
  # FixIt 0.3.0 | NEW page heading config
  [page.heading]
    # FixIt 0.3.12 | CHANGED must set `params.page.toc.ordered` to true
    [page.heading.number]
      # whether to enable auto heading numbering
      enable = true
      # FixIt 0.3.3 | NEW only enable in main section pages (default is posts)
      onlyMainSection = true
      [page.heading.number.format]
        h1 = "{title}"
        h2 = "{h2} {title}"
        h3 = "{h2}.{h3} {title}"
        h4 = "{h2}.{h3}.{h4} {title}"
        h5 = "{h2}.{h3}.{h4}.{h5} {title}"
        h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"
  # FixIt 0.2.16 | CHANGED KaTeX mathematical formulas
  [page.math]
    enable = false
    # default inline delimiter is $ ... $ and \( ... \)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # default block delimiter is $$ ... $$, \[ ... \], \begin{equation} ... \end{equation} and some other functions
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # KaTeX extension copy_tex
    copyTex = true
    # KaTeX extension mhchem
    mhchem = true
  # Code config
  [page.code]
    # whether to show the copy button of the code block
    copy = true
    # FixIt 0.2.13 | NEW whether to show the edit button of the code block
    edit = true
    # the maximum number of lines of displayed code by default
    maxShownLines = 50
  # Mapbox GL JS config
  [page.mapbox]
    # access token of Mapbox GL JS
    accessToken = ""
    # style for the light theme
    lightStyle = "mapbox://styles/mapbox/light-v9"
    # style for the dark theme
    darkStyle = "mapbox://styles/mapbox/dark-v9"
    # whether to add NavigationControl
    navigation = true
    # whether to add GeolocateControl
    geolocate = true
    # whether to add ScaleControl
    scale = true
    # whether to add FullscreenControl
    fullscreen = true
  # FixIt 0.3.0 | NEW [Experimental] cache remote images locally, see: https://github.com/hugo-fixit/FixIt/pull/362
  [page.cacheRemoteImages]
    enable = false
    # replace remote image URL with local image url (place in public/images/remote/)
    replace = false
  # FixIt 0.3.0 | NEW Related content config
  [page.related]
    enable = true
    count = 5
  # FixIt 0.2.17 | NEW Donate (Sponsor) settings
  [page.reward]
    enable = true
    animation = true
    # position relative to post footer, optional value: ["before", "after"]
    position = "before"
    comment = "Buy me a coffee~"
    # FixIt 0.2.18 | NEW display mode of QR code images, optional values: ["static", "fixed"], default: `static`
    mode = "fixed"
    [page.reward.ways]
      wechatpay = "/images/wechatpay.jpg"
      alipay = "/images/alipay.jpg"
      # paypal = "/images/paypal.png"
      # bitcoin = "/images/bitcoin.png"





[customPartials]

    profile = [
    "custom/profile.html",
  ]


# Auto translation configuration
# See: https://github.com/xnx3/translate/
[autoTranslate]
  enable = true
  # The translation service provider, ['client.edge', 'translate.service']
  # See: https://translate.zvo.cn/43086.html
  service = 'translate.service'
  # List of language ID to translate to, e.g. ["english", "chinese_simplified", "chinese_traditional", ...]
  # If not set, it will be translated to all languages
  # See the full language list: https://api.translate.zvo.cn/language.json
  languages = [
    'chinese_simplified',
    'chinese_traditional',
    'english',
  ]
  # Element IDs that needs to be ignored for translation, e.g. ["comment", ...]
  ignoreID = []
  # Class names that need to be ignored for translation, e.g. ["post-category", ...]
  ignoreClass = []
  # Tag names that need to be ignored for translation, e.g. ["title", ...]
  ignoreTag = []
  # Selectors that need to be ignored for translation, e.g. ["[data-adapters='projects'] .single-subtitle", ...]
  ignoreSelector = []
  # Texts that need to be ignored for translation, e.g. ["FixIt", "Lruihao", ...]
  ignoreText = [
    'https://01235670.xyz',
    'SevenD',
  ]
  # Whether to detect the local language
  detectLocalLanguage = true
  # translate.js CDN
  cdn = ""
  # Whether to enable Enterprise-level translation channel
  # If set to true, automatically switch to the best translation service
  enterprise = false
