# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/theme-documentation-basics/#site-configuration
# -------------------------------------------------------------------------------------

# which hash function used for SRI, when empty, no SRI is used
# ("sha256", "sha384", "sha512", "md5")
# fingerprint = "sha256"

# Comment config


# FixIt 0.3.10 | NEW Busuanzi count
[busuanzi]
  # whether to enable busuanzi count
  enable = true
  # busuanzi count core script source. Default is https://vercount.one/js
  source = "https://vercount.one/js"
  # whether to show the site views
  siteViews = true
  # whether to show the page views
  pageViews = true

# CDN config for third-party library files
[cdn]
  # CDN data file name, disabled by default ["jsdelivr.yml", "unpkg.yml", ...]
  # located in "themes/FixIt/assets/data/cdn/" directory
  # you can store your own data files in the same path under your project: "assets/data/cdn/"
  data = "unpkg.yml"

# FixIt 0.2.10 | NEW Analytics config
[analytics]
  enable = true
  # My share URL: https://cloud.umami.is/share/FSPwm1IsrQFY7ZvP/lruihao.cn
  [analytics.umami]
    # data_website_id = "4049c0b0-87c9-4573-8ae5-d84449e40e05"
    src = "https://cloud.umami.is/script.js"
    data_host_url = ""
    data_domains = ""
